[package]
name = "canoa"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ureq = { version="2.9.7", default_features=false, features=["tls", "json"] }
